<?php

/**
 * Implements hook_permission().
 */
function form_example_permission()
{
    return array(
        'submit_form_example' => array(
            'title' => t('Submit form_example_form'),
            'description' => t('Submit the form_example_form'),
        ),
        'access_form_example_submissions' => array(
            'title' => t('access_form_example_submission'),
            'description' => t('access_form_example_submission'),
        ),
    );
}


/**
 * Implements hook_menu().
 */
function form_example_menu()
{
    $items = array();
    $items['form_example'] = array(
        'title' => 'My Example Form',
        'type' => MENU_NORMAL_ITEM,
        'access arguments' => array('access form_example'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('form_example_form'),
    );
    $items['form_submissions'] = array(
        'title' => 'My Form Submissions',
        'type' => MENU_NORMAL_ITEM,
        'access arguments' => array('access access_form_example_submissions'),
        'page callback' => 'form_example_submissions',
    );
    return $items;
}

/**
 * Implements hook_form().
 */
function form_example_form($node, &$form_state)
{
    $form['mynumber'] = array(
        '#type' => 'textfield',
        '#title' => t('My Number'),
        '#size' => 10,
        '#maxlength' => 10,
        '#required' => TRUE,
        '#description' => t('Please enter a vlaid number'),
    );
    $form['mytextfield'] = array(
        '#type' => 'textfield',
        '#title' => t('My Textfiled'),
        '#size' => 60,
        '#maxlength' => 120,
        '#required' => TRUE,
    );
    $form['mytext'] = array(
        '#type' => 'textarea',
        '#title' => t('My Textarea'),
        '#description' => t('Enter some text'),
        '#default_value' => '',
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Add item'),
    );
    return $form;
}

/*
 * Validation handler for the form example form
 */
function form_example_form_validate($form, &$form_state)
{
    if (!is_numeric($form_state['values']['mynumber'])) {
        form_set_error('mynumber', t('You must enter a vlaid number'));
        return FALSE;
    }
    return TRUE;
}


function form_example_form_submit($form, &$form_state)
{
    $fe_id = db_insert('form_example')
        ->fields(array(
                'mynumber' => $form_state['values']['mynumber'],
                'mytextfield' => $form_state['values']['mytextfield'],
                'mytext' => $form_state['values']['mytext'],
            )
        )->execute();
    drupal_set_message(t('Your form entry has been added'));
}

/*
 * View the form submissions
 */
function form_example_submissions()
{

    //Very simple way to query database, it is fast but not flexiable, db_select tends to be better for more complex stuff even though it is slower.
    //$results = db_query("SELECT * FROM {form_example}");

    $query = db_select('form_example', 'fe');
    $query
        ->fields('fe', array('fe_id', 'mynumber', 'mytextfield', 'mytext'))
        ->range(0, 50)
        //You can set ASC or DESC
        ->orderBy('fe.fe_id');
    $results = $query->execute();

    $header = array(t('ID'), t('My Number'), t('My Textfield'), t('My Text(area)'));
    $rows = array();

    foreach ($results as $result) {
        $rows[] = array(
            check_plain($result->fe_id),
            check_plain($result->mynumber),
            check_plain($result->mytextfield),
            check_markup($result->mytext),
        );
    }
    return theme('table', array('header' => $header, 'rows' => $rows));
}

